services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: inventaire
      POSTGRES_USER: inventaire
      POSTGRES_PASSWORD: inventaire_pwd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./apps/api
    environment:
      DATABASE_URL: postgresql://inventaire:inventaire_pwd@db:5432/inventaire
      JWT_ACCESS_SECRET: change_me_access
      JWT_REFRESH_SECRET: change_me_refresh
      CORS_ORIGIN: http://localhost:5175
      SIGNATURES_DIR: /app/uploads/signatures
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - signatures:/app/uploads/signatures

  # web:
  #   build: ./apps/web
  #   depends_on:
  #     - api
  #   ports:
  #     - "5173:80"

volumes:
  pgdata:
  signatures:
